### PR TITLE
Fix download URL check.

### PR DESCRIPTION
**Pull request by vanzin**
Need to use the URL, not the download path, in the curl command.

### CODE REVIEW

**Comment by gumdelli** [comment]
@Antiarchitect can you please check this PR? master is failing all of our jenkins builds that are dependent on this plugin

**Comment by vanzin** [comment]
For anyone looking for a workaround, I added the following temporarily to stop the breakage in our internal CI:

```
asdf plugin update helm c1760a007d8a06f89f39ac59187cb6245ebbf365
```

**Comment by amontalban** [comment]
Same here

**Comment by vanzin** [comment]
BTW this is a quick & dirty fix to the problem, but it really looks sub-optimal to download the archive twice in the non-M1 case...

**Comment by Antiarchitect** [comment]
Please check :)

**Pull request merged**
